import {
  Github,
  Linkedin,
  Twitter,
  Mail,
} from "lucide-react";

export const PORTFOLIO_CONTENT = {
  personal: {
    name: "Hi, I'm Paras —",
    surname: "A Full Stack web developer.",
    location: "India",
    timezone: "IST",
    bio: `I build interactive web applications using TypeScript, React, Next.js, Node.js and PostgreSQL — with a strong focus on clean UI.`,
    email: "parasverma7454@gmail.com",
    availability: "Available for freelance",
    avatar: "luffy.jpg",
  },
  socials: [
    {
      icon: Github,
      href: "https://github.com/paras-verma7454",
      label: "GitHub",
    },
    {
      icon: Linkedin,
      href: "https://www.linkedin.com/in/paras-vermaa/",
      label: "LinkedIn",
    },
    { icon: Twitter, href: "https://x.com/ParasVerma7454", label: "Twitter" },
    { icon: Mail, href: "mailto:parasverma7454@gmail.com", label: "Email" },
  ],
  skills: [
    "Next.js",
    "React",
    "TypeScript",
    "JavaScript",
    "Node.js",
    "Prisma ORM",
    "Supabase",
    "Tailwind CSS",
    "Docker",
    "Redux",
    "Postman",
    "PostgreSQL",
    "MongoDB",
    "Git",
    "GitHub",
  ],
  experience: [
    {
      company: "Jspark AI",
      companyUrl: "https://jspark.ai",
      role: "SDE Intern",
      period: "Nov 2025 - Present",
      startDate: "2025-11-01",
      description: "Building scalable AI solutions.",
      linkedin: "https://linkedin.com/company/jsparkai",
    },
  ],
  projects: [
    {
      title: "Ossium",
      desc: "An open-source tool to explore trending GitHub projects. Quickly find and filter repositories by language and popularity without complex queries or bloated UIs.",
      tags: ["Next.js","Drizzle ORM","Tailwind CSS","TypeScript","GitHub API"],
      color: "bg-white",
      href: "https://ossium.live/",
      github: "https://github.com/OssiumOfficial",
      className: "md:col-span-1",
      collaborative: true,
      // featured: true,
    },
    {
      title: "CalMarshal",
      desc: "Full-stack scheduling app with Google Calendar sync.",
      tags: ["Next.js", "Prisma", "Nylas", "Next.js"],
      color: "bg-purple-500",
      href: "https://cal-marshal-phi.vercel.app",
      github: "https://github.com/paras-verma7454/CalMarshal",
      className: "md:col-span-1",
    },
    {
      title: "Dionysus",
      desc: "AI dev assistant for code analysis & meetings.",
      tags: ["Gemini API", "Supabase", "Assembly AI", "Next.js"],
      color: "bg-emerald-500",
      href: "https://dionysus-zeta.vercel.app/",
      github: "https://github.com/paras-verma7454/Dionysus",
      className: "md:col-span-1",
    },
    {
      title: "Bolt New",
      desc: "A prompt-based frontend builder that generates production-ready React components using natural language.",
      tags: ["Convex", "Next.js", "Gemini", "Tailwind", "Code sandbox"],
      color: "bg-orange-500",
      href: "https://bolt-new-olive.vercel.app/",
      github: "https://github.com/paras-verma7454/bolt.new",
      className: "md:col-span-1",
    },
    {
      title: "DriveDeck",
      desc: "Buy & Sell Cars Without the Friction.",
      tags: ["React.js", "Node.js", "PostgreSQL"],
      color: "bg-purple-300",
      href: "https://drive-deck.vercel.app/",
      github: "https://github.com/paras-verma7454/DriveDeck",
      className: "md:col-span-1",
    },
    {
      title: "Chat App",
      desc: "Chat app build with web sockets.",
      tags: ["React.js", "Node.js", "WebSockets"],
      color: "bg-green-300",
      href: "https://github.com/paras-verma7454/chat-app",
      github: "https://github.com/paras-verma7454/chat-app",
      className: "md:col-span-1",
    },
    {
      title: "Paytm",
      desc: "A full-stack digital wallet application, featuring secure money transfers and user authentication.",
      tags: ["React.js", "Node.js", "MongoDB"],
      color: "bg-blue-300",
      href: "https://paytm-livid.vercel.app/",
      github: "https://github.com/paras-verma7454/Paytm",
      className: "md:col-span-1",
    },
    {
      title: "Medium",
      desc: "A full-stack digital wallet application, featuring secure money transfers and user authentication.",
      tags: ["React.js", "Hono", "Prisma ORM"],
      color: "bg-gray-700",
      href: "https://medium-kappa-nine.vercel.app/",
      github: "https://github.com/paras-verma7454/Medium",
      className: "md:col-span-1",
    },
  ],
  contributions: [
    { prUrl: "https://github.com/fastapi/fastapi/pull/14565" },
    { prUrl: "https://github.com/ig-imanish/mx-icons/pull/9" },
  ],
};
